Added getifaddrs OSX bindings
dlang/druntime pull request #3215
Opened 2020-09-23 05:03 UTC by ferencdg

2020-09-25 04:09 UTC, Geod24 requested changes

2020-09-25 10:17 UTC, jacob-carlborg requested changes

2020-09-25 10:17 UTC, jacob-carlborg commented on src/core/sys/darwin/ifaddrs.d
> +version (OSX):
The package name contains `darwin` but the version statement says `OSX`. Please add version statements for other Darwin platforms as well, like this: https://github.com/dlang/druntime/blob/17fb8437d4444e212a1a7c79792052abfcda007a/src/core/sys/darwin/dlfcn.d#L12-L21

2020-09-25 10:17 UTC, jacob-carlborg commented on src/core/sys/darwin/ifaddrs.d
> +void freeifaddrs(ifaddrs* );
What about the `getifmaddrs` and `freeifmaddrs` functions?

2020-10-05 05:22 UTC, Geod24 commented
Ping @ferencdg

2020-10-06 09:24 UTC, ferencdg commented
made the suggested changes, thanks for the comments

2020-10-06 14:38 UTC, jacob-carlborg approved these changes

2020-10-09 06:07 UTC, thewilsonator commented
```
grep -n -U -P "([ \t]$|\r)" $list_of_files ; test "$?" -ne 0
src/core/sys/darwin/ifaddrs.d:63:    /// Interface	name (AF_LINK)
src/core/sys/darwin/ifaddrs.d:65:    /// Multicast	address
posix.mak:363: recipe for target 'checkwhitespace' failed
```

please remove the trailing whitespace.

2020-10-09 12:43 UTC, Geod24 commented
> It was actually tabs :|

2020-10-09 12:50 UTC, Geod24 commented
Fixed the tabs and slightly edited the documentation to refer to the header as opposed to just the (original) functions.

2020-10-09 13:21 UTC, merged

2021-02-05 07:28 UTC, Geod24 commented
Urgh, this should have been in `COPY` & co as well...