macOS: add core.sys.darwin.fcntl
dlang/druntime pull request #3372
Opened 2021-02-10 15:32 UTC by kubo39

This is the preparation for https://issues.dlang.org/show_bug.cgi?id=21627.

2021-02-10 15:42 UTC, jacob-carlborg requested changes

2021-02-10 15:42 UTC, jacob-carlborg commented on src/core/sys/darwin/fcntl.d
> +enum F_FULLSYNC = 51;
It's named `F_FULLFSYNC`.

2021-02-10 15:48 UTC, kubo39 commented on src/core/sys/darwin/fcntl.d
> +enum F_FULLSYNC = 51;
Ahh, sorry.

2021-02-11 05:06 UTC, jacob-carlborg approved these changes

2021-02-11 08:44 UTC, RazvanN7 approved these changes

2021-02-11 08:44 UTC, merged