dwarf.d: remove spurious trailing comma
dlang/druntime pull request #3498
Opened 2021-06-14 20:48 UTC by WalterBright

Bad style exploiting what appears to be a bug in the D front end.

2021-06-14 21:06 UTC, WalterBright commented
```
std/stdio.d(299): Error: undefined identifier `flockfile` in module `core.sys.posix.stdio`
```
What the heck? That has nothing to do with this trivial PR.

2021-06-14 21:26 UTC, wilzbach commented
It's not a bug, it's a feature.

2021-06-14 21:55 UTC, WalterBright commented
If it's used exactly once, it's not much of a feature.

2021-06-14 21:56 UTC, CyberShadow commented
More uses here: https://github.com/dlang/dmd/pull/12684#issuecomment-860988350

2021-06-15 06:43 UTC, thewilsonator commented
This might be bad style for just two arguments, but as noted this is a feature not a bug. 
It has the same use as trailing comma for enum declarations.

2021-06-15 06:46 UTC, thewilsonator commented
>What the heck? That has nothing to do with this trivial PR.

How many commits between `trailingComma~1` and `dlang/master`? Maybe try rebasing?

2021-06-15 06:57 UTC, thewilsonator approved these changes

2021-06-15 08:12 UTC, Geod24 requested changes
Not an oversight, very much on purpose, as there is another usage of it in the commit that introduced it:
https://github.com/dlang/druntime/commit/f6534412ac65fb1f343d5a71ec8779faf1c69662#diff-1b94c982760aac40515b2b539895bf36e83f45159711f983f09290277a996587R91-R96

And we established it's not a bug, but a feature introduced 10 years ago as a fix to issue 2477.

2021-06-21 11:31 UTC, DoctorNoobingstoneIPresume commented
FWMOIW (For Whatever My Opinion Is Worth), this feature makes it easier to write some code-generating (`mixin`) code.

Plus, if code is indented like this:

```
f
(
    very-long-arg1,
    veey-long-arg2,
    very-long-arg3,
);
```
that trailing comma ensures we can add `very-long-arg4` without affecting the history of the `very-long-arg3` line.

2021-06-21 12:42 UTC, Geod24 commented
The DMD PR has been closed, so closing this too.

2021-06-21 12:42 UTC, closed without merging