Improve parameters name
dlang/druntime pull request #3516
Opened 2021-07-13 22:09 UTC by ryuukk

2021-07-13 23:54 UTC, Geod24 requested changes
Some of the names, while not great, follow what's on the man page:
- https://man7.org/linux/man-pages/man3/memchr.3.html
- https://man7.org/linux/man-pages/man3/memcmp.3.html

However, that's not the case for all of them: https://man7.org/linux/man-pages/man3/memmove.3.html

I think that we should just follow what the `man` uses, otherwise we'd have to come up with our own convention, which I'm not sure will be a productive usage of everyone's time (do we use `dst` ? `dest` ? `destination` ? etc...)

2021-07-14 12:10 UTC, ryuukk commented
I'd personally just use ``dst`` and ``src``

Waiting to see if more people have ideas before making other changes

2021-07-17 02:24 UTC, n8sh commented on src/core/stdc/string.d
> +int   memcmp(scope const void* dest, scope const void* src, size_t n) pure;
I do not consider this change to be an improvement. Naming the parameters "source" and "destination" implies something is moving from the source to the destination.

2021-08-10 10:28 UTC, RazvanN7 commented
@ryuukk Given that there were only oppositions to these PR, how to you plan to proceed?

2021-08-24 13:13 UTC, closed without merging