fix some compatibility issues for Solaris systems
dlang/druntime pull request #3624
Opened 2021-11-13 20:12 UTC by BarrOff

Hello,

some fixes to aid compilation on Solaris/Illumos based systems.
I successfully tested the changes on a recent Solaris/Illumos installation.

2021-11-13 22:38 UTC, thewilsonator approved these changes

2021-11-13 22:38 UTC, thewilsonator commented
cc @ibuclaw

2021-11-14 08:39 UTC, ibuclaw requested changes

2021-11-14 08:39 UTC, ibuclaw commented on src/core/stdcpp/string_view.d
> +        alias __size = _M_len;
Developer Studio doesn't implement this, so maybe add a pragma saying as much. Falling back on doing what gcc does is the safe option, which seems to be what you're doing here.

2021-11-14 08:39 UTC, ibuclaw commented on src/core/sys/posix/signal.d
> +    enum SIG_SETMASK = 3;
There's a few more wrong values in this file that need fixing up IIRC.

2021-11-14 08:39 UTC, ibuclaw commented on src/core/internal/backtrace/elf.d
> +    import core.sys.solaris.sys.elf;
Some enum values in the elf_i386 and elf_sparc modules need moving to the common elf module for this to compile.

2021-11-16 13:32 UTC, ibuclaw commented on src/core/sys/posix/signal.d
> +    enum SIG_SETMASK = 3;
```
enum SIGIO = SIGPOLL;
enum SIGVTALRM = 28;
enum SIGXFSZ = 31;
```

2021-11-16 13:34 UTC, ibuclaw commented on src/core/internal/backtrace/elf.d
> +    import core.sys.solaris.sys.elf;
`SHF_ORDERED` and `SHF_EXCLUDE` are the definitions to move out of elf_386 and elf_SPARC to the elf module.

2021-11-16 13:34 UTC, ibuclaw commented on src/core/internal/backtrace/elf.d
> +    import core.sys.solaris.sys.elf;
Missing definition of `SHF_COMPRESSED` in the elf module too.

2021-11-16 19:27 UTC, ibuclaw commented on src/core/sys/solaris/sys/elf.d
> +    enum SHF_EXCLUDE = 0x80000000;
This isn't CPU specific anymore, hence why I suggested it be moved to the common elf module.

2021-11-19 07:48 UTC, RazvanN7 commented
@ibuclaw is this good to go?

2021-11-19 07:54 UTC, ibuclaw commented
SIG stuff are already defined elsewhere (with the wrong value), and missing SHF_COMPRESSED.

2021-11-23 16:40 UTC, BarrOff commented
@ibuclaw, @RazvanN7 

> SIG stuff are already defined elsewhere (with the wrong value), and missing SHF_COMPRESSED.

What can/should I still do about the SIG stuff? I already moved `SHF_ORDERED` and `SHF_EXCLUDE` to their correct location. The version check has also been removed.

Concerning `SHF_COMPRESSED`: it is not available in the headers, at least on my Illumos instance, and as far as my research shows on Solaris, too. However, this enum is just used at one place: `processDebugLineSectionData` of core.internal.backtrace.elf.d. We could put a `version(Solaris)` guard around it. But I am no expert with ELF file format, and can not say what needs to change for the Solaris version.

2021-11-23 17:27 UTC, ibuclaw commented
> @ibuclaw, @RazvanN7
> 
> > SIG stuff are already defined elsewhere (with the wrong value), and missing SHF_COMPRESSED.
> 
> What can/should I still do about the SIG stuff? I already moved `SHF_ORDERED` and `SHF_EXCLUDE` to their correct location. The version check has also been removed.
> 

SIGVTALRM and SIGXFSZ are already defined here: https://github.com/dlang/druntime/blob/a17bb23b418405e1ce8e4a317651039758013f39/src/core/sys/posix/signal.d#L2836-L2838

They just have the wrong value.

> Concerning `SHF_COMPRESSED`: it is not available in the headers, at least on my Illumos instance, and as far as my research shows on Solaris, too. However, this enum is just used at one place: `processDebugLineSectionData` of core.internal.backtrace.elf.d. We could put a `version(Solaris)` guard around it. But I am no expert with ELF file format, and can not say what needs to change for the Solaris version.

On Solaris 11.4, it's defined as `0x800` in the `sys/elf.h` header (sandwiched inbetween SHF_TLS and SHF_MASKOS).

2021-11-25 16:39 UTC, BarrOff commented
@ibuclaw 

I fixed the two values and added `SHF_COMPRESSED` at the right place. On Illumos it really is not defined, see [here](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/sys/elf.h). There is simply a blank line between `SHF_TLS` and `SHF_MASKOS`.

If that is ok now, the only remaining problem is the part about `CppRuntime_Sun`.
I don't have access to Developer Studio, and don't know what has to be inserted for `CppRuntime_Sun`.

However, Developer Studio has been replaced by gcc in [OpenIndiana](https://www.openindiana.org/documentation/faq/#how-does-openindiana-differ-from-opensolaris), in [OmniOS also](https://github.com/omniosorg/omnios-build/blob/r151040/doc/ReleaseNotes.md) and I suppose in SmartOS too. The only system still using Developer Studio is the official Oracle Solaris.

To solve this problem I see two possible solutions:

1. a check could be added to see if we have an "Illumos" Solaris version. If we do, use what gcc does. This however does not fix the root of the problem. That is, dmd predefines CppRuntime_Sun on all Solaris systems.
2. Therefore moving such a check to dmd might be more sensible. If the build detects an Illumos system, it should predefine CppRuntime_Gcc instead. Then my change here would not be necessary.

2021-11-25 20:07 UTC, ibuclaw commented
> @ibuclaw 
> 
> I fixed the two values and added `SHF_COMPRESSED` at the right place. On Illumos it really is not defined, see [here](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/sys/elf.h). There is simply a blank line between `SHF_TLS` and `SHF_MASKOS`.
> 

Maybe someone should send a patch in. :-) 
IIUC, the OSS Solaris should be compatible with the proprietary version.


> If that is ok now, the only remaining problem is the part about `CppRuntime_Sun`.
> I don't have access to Developer Studio, and don't know what has to be inserted for `CppRuntime_Sun`.
> 
> However, Developer Studio has been replaced by gcc in [OpenIndiana](https://www.openindiana.org/documentation/faq/#how-does-openindiana-differ-from-opensolaris), in [OmniOS also](https://github.com/omniosorg/omnios-build/blob/r151040/doc/ReleaseNotes.md) and I suppose in SmartOS too. The only system still using Developer Studio is the official Oracle Solaris.
> 
> To solve this problem I see two possible solutions:
> 
> 1. a check could be added to see if we have an "Illumos" Solaris version. If we do, use what gcc does. This however does not fix the root of the problem. That is, dmd predefines CppRuntime_Sun on all Solaris systems.
> 2. Therefore moving such a check to dmd might be more sensible. If the build detects an Illumos system, it should predefine CppRuntime_Gcc instead. Then my change here would not be necessary.

I think it's reasonable to default to CppRuntime_Gcc on Solaris, and use Sun only if requested by the -target triplet.

2021-11-26 08:42 UTC, ibuclaw commented on src/core/sys/posix/signal.d
> +    enum SIGXFSZ = 31;
You can remove these now. :-)

2021-11-30 13:01 UTC, BarrOff commented
@ibuclaw 

I have removed the redundant signals and reverted the change to string_view.d .
I hope this is now ok to be merged? :-)

Besides, I opened a pull request on DMD to default to `CppRuntime_Gcc` on Solaris.

2021-11-30 13:31 UTC, ibuclaw commented on src/core/sys/posix/signal.d
> +    enum SIGIO = SIGPOLL;
I'd move this with the others, but don't think it would be harming anything at this point in time.

2021-11-30 13:31 UTC, ibuclaw approved these changes

2021-11-30 14:10 UTC, merged