Pass args to ctor without `forward` in `_d_newThrowable`
dlang/druntime pull request #3761
Opened 2022-02-24 23:37 UTC by teodutu

`forward` is unnecessary because the parameters of `_d_newThrowable` are already `auto ref`. Removing `forward` does not remove this qualifier from the params, but it does fix linker errors in https://github.com/dlang/dmd/pull/13494/.

2022-02-25 00:25 UTC, MoonlightSentinel requested changes
> forward is unnecessary because the parameters of _d_newThrowable are already auto ref.

The ctor arguments are always lvalues without `forward`. See the first example [here](https://dlang.org/phobos/core_lifetime.html#.forward)

2022-02-25 08:59 UTC, RazvanN7 commented
@MoonlightSentinel Why is that a problem? I don't think that preserving the rvalue status of an argument is relevant in this scenario. I expect that if an object defines both an rvalue and lvalue constructor they do the same thing with the exception that the rvalue one will move the argument whereas the lvalue will simply pass a ref. From a performance standpoint, you can see this as an optimization.

2022-02-26 13:06 UTC, kinke commented
> I don't think that preserving the rvalue status of an argument is relevant in this scenario.

It absolutely is in general; there have been numerous bugs in druntime/Phobos due to *not* forwarding `auto ref` params, e.g., in `emplace` etc., and `_d_newThrowable` is a similar constructor wrapper.

The analysis regarding the actual problem seems to be wrong; removing `forward` is definitely wrong.

2022-02-28 10:19 UTC, RazvanN7 commented
Yes, I absolutely agree that selecting the correct constructor based on lvalueness is important in the general case and obviously this is a template emission problem, however, given that this specific hook is called once an exception is thrown I thought that it might not be relevant from a semantics point of view what constructor is called since the important aspect is that a specific type of exception is thrown.

This was just a hack/workaround so that we can get this hook in, otherwise I fear that we will be stalled by dip1008 issues.

2022-02-28 10:21 UTC, MoonlightSentinel commented
> @MoonlightSentinel Why is that a problem? 

Adhering to the language specification. A constructor call with r/lvalue *must* call the corresponding r/lvalue constructor in case of overloads based on lvalue-ness. Period.

> From a performance standpoint, you can see this as an optimization.

That assumptions doesn't hold if an object passed by `ref` may need a deep copy, e.g. for a container. `move`'d instances could simply take ownership of the underlying data.

But then again, this discussion is pointless because the proposed change violates the language rules.

2022-02-28 10:23 UTC, MoonlightSentinel commented
> This was just a hack/workaround [...]

That is likely to break again due to slight changes in the order of semantic analysis / template emission strategy.

2022-02-28 10:24 UTC, RazvanN7 commented
> That assumptions doesn't hold if an object passed by ref may need a deep copy, e.g. for a container. move'd instances could simply take ownership of the underlying data.

We are talking about exceptions here. I can hardly think of a scenario where that would be necessary.

2022-02-28 10:25 UTC, RazvanN7 commented
@MoonlightSentinel There is no doubt that you are correct, however, at this point we don't have any other solution for this situation.

2022-02-28 10:48 UTC, RazvanN7 commented
For reference, this [1] is what's stopping phobos to compile with dip1008.

[1] https://github.com/dlang/dmd/pull/10561

2022-03-03 11:19 UTC, closed without merging